const BREAKFAST_DATA = [
  { "id": 1,  "date": "2026-09-01", "name": "Banános zabpalacsinta",                              "ingredients": [] },
  { "id": 2,  "date": "2026-09-02", "name": "Almás-zabos mini muffin",                            "ingredients": [] },
  { "id": 3,  "date": "2026-09-03", "name": "Avokádócsíkok és kenyércsík",                        "ingredients": [] },
  { "id": 4,  "date": "2026-09-04", "name": "Fehérbabkrém kenyérre kenve",                        "ingredients": [] },
  { "id": 5,  "date": "2026-09-05", "name": "Vöröslencsekrém pirítóscsíkokra",                   "ingredients": [] },
  { "id": 6,  "date": "2026-09-06", "name": "Köleskása puhára főzve körtedarabokkal",             "ingredients": [] },
  { "id": 7,  "date": "2026-09-07", "name": "Zabkása sült almával",                               "ingredients": [] },
  { "id": 8,  "date": "2026-09-08", "name": "Tofu rántotta puha kenyérrel",                       "ingredients": [] },
  { "id": 9,  "date": "2026-09-09", "name": "Sült körte zabpehellyel",                            "ingredients": [] },
  { "id": 10, "date": "2026-09-10", "name": "Babos mini pogácsa",                                 "ingredients": [] },
  { "id": 11, "date": "2026-09-11", "name": "Csicseriborsós pogácsa",                             "ingredients": [] },
  { "id": 12, "date": "2026-09-12", "name": "Vöröslencsés fasírtgolyók",                         "ingredients": [] },
  { "id": 13, "date": "2026-09-13", "name": "Cukkinifasírt",                                      "ingredients": [] },
  { "id": 14, "date": "2026-09-14", "name": "Brokkolis zabfasírt",                                "ingredients": [] },
  { "id": 15, "date": "2026-09-15", "name": "Sült édesburgonya hasábok",                         "ingredients": [] },
  { "id": 16, "date": "2026-09-16", "name": "Paradicsomos vöröslencsés tészta",                  "ingredients": [] },
  { "id": 17, "date": "2026-09-17", "name": "Apró tészta fehérbabos szósszal",                   "ingredients": [] },
  { "id": 18, "date": "2026-09-18", "name": "Bulgur párolt répával",                              "ingredients": [] },
  { "id": 19, "date": "2026-09-19", "name": "Bulgur cukkinikockákkal",                            "ingredients": [] },
  { "id": 20, "date": "2026-09-20", "name": "Zöldséges rizs (répa, borsó)",                      "ingredients": [] },
  { "id": 21, "date": "2026-09-21", "name": "Gombás rizs finomra vágott gombával",               "ingredients": [] },
  { "id": 22, "date": "2026-09-22", "name": "Lencsefőzelék sűrűre főzve",                        "ingredients": [] },
  { "id": 23, "date": "2026-09-23", "name": "Burgonyafőzelék fasírtgolyókkal",                   "ingredients": [] },
  { "id": 24, "date": "2026-09-24", "name": "Karfiolos-rizses egytálétel",                       "ingredients": [] },
  { "id": 25, "date": "2026-09-25", "name": "Párolt brokkoli és sült burgonya",                  "ingredients": [] },
  { "id": 26, "date": "2026-09-26", "name": "Zöldségleves sűrűn, sok puhára főtt zöldséggel",   "ingredients": [] },
  { "id": 27, "date": "2026-09-27", "name": "Babos rizottó",                                      "ingredients": [] },
  { "id": 28, "date": "2026-09-28", "name": "Zöldséges bulgurpogácsa",                           "ingredients": [] },
  { "id": 29, "date": "2026-09-29", "name": "Lecsó rizzsel (enyhe, sótlan változat)",            "ingredients": [] },
  { "id": 30, "date": "2026-09-30", "name": "Tepsis zöldségek (répa, cukkini, karfiol) bulgurral", "ingredients": [] }
];
